 c @extends('layouts.hf')
@section('title', 'Pricing || Kunnec ')
@section('content')
 <div class="container-fluid">
     	<center>
     		<h1><font color="grey" size="+5">Kunnec Pricing and Payments</font></h1>
    	 	<p>All of our transactions are done through Paypal</p>
    	 	<hr />
     	</center>
    	<div class="accordion vertical">
          <section id="vertabout">
              <br />
              <h2><a href="#vertabout">Why isn't Kunnec Free?</a></h2>
              <p>We value everyone who uses Kunnec and we don't want to take any of our users for granted. Kunnec is created by independent minded people, just like you, and we want your experience to be of great quality, fast and exactly what you want.  We don't have advertising on the site and never will. Advertising diminishes the user experience. In order for Kunnec not to have advertising, we must charge a small fee per year to each user. </p>
          </section>
          <section id="vertservices">
              <br />
              <h2><a href="#vertservices">Credits</a></h2>
              <p>After selecting the plan that fits what you want to do on Kunnec, you must purchase credits. Credits are used throughout the entire site, so the user can have a free flowing experience. Each credit has a value of 20 cents. The lowest limit to start your credit balance is $5.00, which gives you 25 credits. The highest limit of purchasing credits is $75.00. You can purchase credits at anytime, it is up to you. There isn't a monthly fee to use Kunnec. You can also send credits between users. This is our gift credit program.</p>
          </section>
          <section id="vertblog">
              <br />
              <h2><a href="#vertblog">Credit Value Setting</a></h2>
              <p>The value of kunnec different services is set by you the user. You determine what your content is worth. We just provide the platform to do it.</p>
          </section>
          <section id="vertportfolio">
              <br />
              <h2><a href="#vertportfolio">Payment</a></h2>
              <p>The credits generated by you from different users will be transfered to your paypal account monthly in dollar amounts. 60% goes to you and 40% goes to kunnec, so we can maintain the functionality of the site and add more options in the future. For example, if you generated 300 credits within that month, $36 dollars is transferred to your paypal account and $24 dollars goes to Kunnec. </p>
          </section>
          <section id="vertcontact">
              <br />
              <h2><a href="#vertcontact">Payment Scale</a></h2>
              <p>The first year the payout is 60% to you and 40% to Kunnec.</p>
              <p> The second year payout is 75% to you and 25% to Kunnec.</p>
              <p> The third year payout is 90% to you and 10% to Kunnec.</p>
              <p> After the third year and forever, the payout is 90% to you and 10% to Kunnec.</p>
          </section>
      </div>
</div>
@endsection